services:
  - type: web
    name: ruin-of-odin
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 3001
      - key: NODE_ENV
        value: production
