import { useEffect, useMemo, useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { ArrowLeft, ArrowRight, BookOpen, Check, ChevronRight, Copy, Crown, Flame, Heart, Layers3, Shield, Sparkles, Swords, Volume2, VolumeX, Wifi, X, Zap } from 'lucide-react';
import { CARDS, DECK, LANES, coreArt, opponent, type CardInstance, type GameEvent, type GameView, type Lane, type PlayerId, type Unit } from '@core-battle/shared';
import { art } from './assets';
import { availableActions, restoreRoom, useGame } from './store';

function Rune({ small = false }: { small?: boolean }) { return <span className={`rune ${small ? 'small' : ''}`} aria-hidden="true">ᛟ</span>; }
function Card({ card, selected, disabled, onClick, compact = false }: { card: CardInstance; selected?: boolean; disabled?: boolean; onClick?: () => void; compact?: boolean }) {
  const definition = CARDS[card.cardId];
  return <motion.button layout initial={{ opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -35, scale: 0.8 }} whileHover={disabled ? {} : { y: -10 }} className={`card ${definition.type.toLowerCase()} ${selected ? 'selected' : ''} ${compact ? 'compact' : ''}`} disabled={disabled} onClick={onClick} aria-label={`${definition.name}, ${definition.cost} mana${definition.type === 'UNIT' ? `, ${definition.attack} attack, ${definition.hp} health` : ''}`} aria-pressed={selected} title={definition.description}>
    <span className="card-cost">{definition.cost}</span><div className="card-art"><img src={art(definition.art)} alt="" /></div>
    <div className="card-copy"><span className="card-kind">{definition.type === 'UNIT' ? 'UNIT' : 'SPELL'}</span><strong>{definition.name}</strong><p>{definition.description}</p></div>
    <div className="card-footer">{definition.type === 'UNIT' ? <><span><Swords size={12} />{definition.attack}</span><span><Heart size={12} />{definition.hp}</span></> : <span><Sparkles size={12} />{definition.id === 'lightning' ? 'ALL ENEMIES' : 'TARGET UNIT'}</span>}</div>
  </motion.button>;
}
function Rules({ close }: { close: () => void }) {
  return <div className="modal-backdrop" onClick={close}><section className="modal rules" role="dialog" aria-modal="true" aria-labelledby="rules-title" onClick={e => e.stopPropagation()}><button className="icon-button modal-close" onClick={close} aria-label="Close rules"><X /></button><span className="eyebrow">THE FIELD GUIDE</span><h2 id="rules-title">Sequential turns. Endless strategy.</h2><div className="rule-grid"><article><Swords /><h3>Protect your core</h3><p>Both cores start at 30 HP. Control three lanes and bring the enemy core to zero. Each side can place one unit per lane.</p></article><article><Layers3 /><h3>Sequential turns</h3><p>Players alternate turns (Turn 1, Turn 2, etc.). When you end your turn, auto-combat immediately triggers for your ready units!</p></article><article><Zap /><h3>Mana & card draw</h3><p>Draw 1 card at the start of every turn (max hand: 7). Mana increases each turn (+1 max mana up to 10) and refills fully.</p></article><article><Shield /><h3>Attacking & defending</h3><p>Active player is the attacker. Defending units deal counter damage in the same lane. Empty opposing lanes let your units hit the enemy Core.</p></article><article><Sparkles /><h3>Summoning & status</h3><p>Units cannot attack on the turn summoned. On Turn 1 (First Player), no units can attack. Freeze stops attacks; Poison deals 2 damage before combat.</p></article><article><Flame /><h3>Sudden death</h3><p>Starting on Turn 21, both cores take 2 direct damage at the start of each combat phase until a victor emerges.</p></article></div><button className="primary" onClick={close}>I’m ready <ArrowRight size={16} /></button></section></div>;
}
function Menu() {
  const { startBot, createRoom, joinRoom, busy } = useGame();
  const [difficulty, setDifficulty] = useState<'easy' | 'normal'>('normal');
  const [code, setCode] = useState('');
  return <main className="lobby"><div className="hero"><div className="hero-copy"><span className="eyebrow"><span className="live-dot" /> A TACTICAL CARD BATTLE</span><h1>Small battlefield.<br /><em>Legendary battles.</em></h1><p>Summon your warriors. Command the elements.<br />Three lanes stand between you and their core.</p><div className="hero-facts"><span><Swords size={16} /> 3 lanes</span><span><Layers3 size={16} /> 30 cards</span><span><Heart size={16} /> 1 core to protect</span></div></div><div className="hero-art"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><Rune /><img src={art(coreArt(30))} alt="The magic crystal core" /><span className="hero-art-caption">THE HEART OF YOUR KINGDOM</span></div></div>
    <div className="mode-grid"><section className="mode-panel bot-panel"><span className="panel-number">01 / SOLO</span><div className="mode-heading"><Shield size={25} /><h2>Hone your strategy</h2></div><p>Challenge the guardian. Learn the cards.<br />Make every round count.</p><div className="difficulty" role="group" aria-label="Bot difficulty"><button className={difficulty === 'easy' ? 'active' : ''} onClick={() => setDifficulty('easy')}>Easy <span>Learn the ropes</span></button><button className={difficulty === 'normal' ? 'active' : ''} onClick={() => setDifficulty('normal')}>Normal <span>A worthy rival</span></button></div><button className="primary" onClick={() => startBot(difficulty)} disabled={busy}>Play against bot <ArrowRight size={17} /></button><span className="panel-note">Ready when you are. No connection needed.</span></section>
    <section className="mode-panel"><span className="panel-number">02 / MULTIPLAYER</span><div className="mode-heading"><Swords size={25} /><h2>Challenge a friend</h2></div><p>A private battlefield for two.<br />No accounts. Just a room code.</p><button className="secondary create-room" onClick={() => void createRoom()} disabled={busy}>{busy ? 'Connecting…' : 'Create a room'}<ChevronRight size={17} /></button><div className="divider"><span>OR JOIN A BATTLE</span></div><form onSubmit={e => { e.preventDefault(); void joinRoom(code); }} className="join-form"><input aria-label="Room code" placeholder="ENTER CODE" value={code} onChange={e => setCode(e.target.value.toUpperCase().replace(/[^A-Z0-9]/g, '').slice(0, 6))} maxLength={6} /><button className="secondary" disabled={code.length !== 6 || busy} type="submit">Join <ArrowRight size={16} /></button></form><span className="panel-note"><Wifi size={12} /> Live, turn-based multiplayer</span></section></div><footer className="lobby-footer"><span>BUILT FOR THE BATTLE. NO GRIND REQUIRED.</span><span>5–10 MINUTES / MATCH</span></footer></main>;
}
function WaitingRoom() {
  const { room, connected, leave } = useGame(); const [copied, setCopied] = useState(false);
  const copy = async () => { if (!room) return; try { await navigator.clipboard.writeText(room.code); setCopied(true); setTimeout(() => setCopied(false), 1800); } catch { setCopied(false); } };
  return <main className="waiting"><Rune /><span className="eyebrow">YOUR BATTLEFIELD IS READY</span><h1>{room?.status === 'CLOSED' ? 'This room has closed' : !connected ? 'Connecting to the battlefield…' : 'Waiting for your rival'}</h1><p>Share this code with a friend. The battle begins when they join.</p>{room && <button className="room-code" onClick={() => void copy()} aria-label={`Copy room code ${room.code}`}>{room.code}{copied ? <Check size={20} /> : <Copy size={20} />}</button>}<span className="waiting-status"><span className="live-dot" />{connected ? '1 / 2 players connected' : 'Reconnecting…'}</span><button className="text-button" onClick={() => void leave()}><ArrowLeft size={15} /> Back to home</button></main>;
}
function Core({ view, player, enemy }: { view: GameView; player: PlayerId; enemy: boolean }) {
  const { events, batch } = useGame(); const p = view.players[player];
  const hits = events.filter(e => e.type === 'CORE_DAMAGED' && e.player === player); const amount = hits.reduce((n, e) => n + (e.amount ?? 0), 0);
  return <div className={`core-status ${enemy ? 'enemy-core' : 'your-core'} ${p.coreHp <= 6 ? 'critical' : ''}`}><motion.div key={`${batch}-${player}`} className="core-image" animate={amount ? { x: [0, -5, 5, -3, 0] } : {}}><img src={art(coreArt(p.coreHp))} alt={`${enemy ? 'Enemy' : 'Your'} core`} />{amount > 0 && <motion.span className="damage-number" initial={{ y: 0, opacity: 1 }} animate={{ y: -32, opacity: 0 }} transition={{ duration: 1.3 }}>−{amount}</motion.span>}</motion.div><div className="core-info"><span className="eyebrow">{enemy ? 'ENEMY CORE' : 'YOUR CORE'}</span><div className="core-health"><Heart size={15} /><strong>{p.coreHp}</strong><span>/ 30</span></div><div className="health-track"><motion.div animate={{ width: `${p.coreHp / 30 * 100}%` }} /></div></div></div>;
}
function UnitSlot({ unit, lane, enemy, targetable, onClick, round }: { unit: Unit | null; lane: Lane; enemy: boolean; targetable: boolean; onClick: () => void; round: number }) {
  const { events, batch } = useGame();
  const related = events.filter(e => e.targetId === unit?.id);
  const damage = related.filter(e => e.type === 'DAMAGE_DEALT').reduce((n, e) => n + (e.amount ?? 0), 0);
  const attacks = related.some(e => e.type === 'ATTACK');
  return <div className={`unit-slot ${enemy ? 'enemy-slot' : 'friendly-slot'} ${targetable ? 'targetable' : ''}`}><AnimatePresence mode="wait">{unit ? <motion.button key={unit.id} className={`board-unit ${unit.statuses.some(s => s.type === 'FREEZE') ? 'frozen' : ''} ${unit.statuses.some(s => s.type === 'POISON') ? 'poisoned' : ''}`} initial={{ opacity: 0, scale: 0.7, y: enemy ? -15 : 15 }} animate={{ opacity: 1, scale: 1, y: 0 }} exit={{ opacity: 0, scale: 0.7, filter: 'grayscale(1)' }} onClick={onClick} disabled={!targetable} aria-label={`${enemy ? 'Enemy' : 'Friendly'} ${CARDS[unit.cardId].name} in lane ${lane + 1}`} title={CARDS[unit.cardId].description}><motion.div key={`${unit.id}-${batch}`} animate={attacks ? { y: [0, enemy ? 12 : -12, 0] } : damage ? { x: [0, -4, 4, 0] } : {}}><img src={art(CARDS[unit.cardId].art)} alt="" /><span className="unit-name">{CARDS[unit.cardId].name}</span><div className="unit-stats"><span><Swords size={12} />{unit.attack}</span><span className={unit.hp < unit.maxHp ? 'hurt' : ''}><Heart size={12} />{unit.hp}</span></div></motion.div><div className="unit-effects">{unit.summonedRound === round && <span>SUMMONED</span>}{unit.statuses.map(s => <span key={s.type} className={s.type.toLowerCase()}>{s.type === 'FREEZE' ? 'FROZEN' : 'POISON'} · {s.remainingCombatPhases}</span>)}</div>{damage > 0 && <motion.span key={batch} className="damage-number" initial={{ opacity: 1, y: 0 }} animate={{ opacity: 0, y: -35 }} transition={{ duration: 1.2 }}>−{damage}</motion.span>}</motion.button> : <motion.button key="empty" className="empty-slot" onClick={onClick} disabled={!targetable} aria-label={`${enemy ? 'Enemy' : 'Friendly'} empty lane ${lane + 1}`} initial={{ opacity: 0 }} animate={{ opacity: 1 }}><span className="slot-rune">ᛟ</span><span>{targetable ? 'SUMMON HERE' : 'EMPTY LANE'}</span></motion.button>}</AnimatePresence></div>;
}
function eventText(event: GameEvent, you: PlayerId): string {
  const who = event.player === you ? 'You' : 'Rival'; const name = event.cardId ? CARDS[event.cardId].name : '';
  switch (event.type) {
    case 'ROUND_STARTED': return `Turn ${event.round} begins`;
    case 'COMBAT_STARTED': return `Turn ${event.round} · Combat`;
    case 'CARD_DRAWN': return `You drew ${name}`;
    case 'CARD_BURNED': return `${name} discarded · hand full`;
    case 'UNIT_SUMMONED': return `${who} summoned ${name}`;
    case 'SPELL_CAST': return `${who} cast ${name}`;
    case 'UNIT_DIED': return `${who === 'You' ? 'Your' : 'Rival’s'} ${name} fell`;
    case 'CORE_DAMAGED': return `${who === 'You' ? 'Your' : 'Enemy'} core −${event.amount} HP`;
    case 'STATUS_APPLIED': return `${event.status === 'FREEZE' ? 'Freeze' : 'Poison'} applied`;
    case 'TOKEN_USED': return `${who} used a tactic token`;
    case 'GAME_WON': return `${who} won the battle`;
    case 'GAME_DRAW': return 'Both cores fell · Draw';
    default: return '';
  }
}
function Battle() {
  const { view, mode, room, difficulty, busy, connected, act, botStep, log, leave, startBot, concede, batch, events } = useGame();
  const [selected, setSelected] = useState<string | null>(null); const [confirm, setConfirm] = useState(false); const [now, setNow] = useState(Date.now());
  useEffect(() => { const timer = setInterval(() => setNow(Date.now()), 1000); return () => clearInterval(timer); }, []);
  useEffect(() => {
    if (mode !== 'bot' || view?.activePlayer !== 1 || view.phase !== 'ACTION') return;
    const timer = setTimeout(botStep, 650); return () => clearTimeout(timer);
  }, [mode, view, botStep]);
  const actions = useMemo(() => view ? availableActions(view) : [], [view]);
  if (!view) return null;
  const you = view.you; const enemy = opponent(you); const hand = view.players[you].hand ?? [];
  const selectedCard = hand.find(c => c.id === selected);
  const ready = view.phase === 'ACTION' && view.activePlayer === you && !busy && (mode === 'bot' || (connected && room?.status === 'PLAYING'));
  const cardActions = actions.filter(a => 'cardInstanceId' in a && a.cardInstanceId === selectedCard?.id);
  const isTarget = (unit: Unit | null, lane: Lane, isEnemy: boolean) => ready && cardActions.some(a => a.type === 'PLAY_UNIT' ? !isEnemy && a.lane === lane : a.type === 'CAST_SPELL' && !!unit && a.targetId === unit.id);
  const target = (unit: Unit | null, lane: Lane, isEnemy: boolean) => {
    const action = cardActions.find(a => a.type === 'PLAY_UNIT' ? !isEnemy && a.lane === lane : a.type === 'CAST_SPELL' && unit && a.targetId === unit.id);
    if (ready && action) { act(action); setSelected(null); }
  };
  const selectCard = (card: CardInstance) => { setSelected(selected === card.id ? null : card.id); };
  const finished = view.phase === 'FINISHED';
  const result = view.winner === 'DRAW' ? 'A battle of equals.' : view.winner === you ? 'The field is yours.' : 'Your core has fallen.';
  const spell = events.find(e => e.type === 'SPELL_CAST');
  return <main className="battle-layout"><section className="battle-main"><div className="battle-heading"><div><span className="eyebrow">{mode === 'bot' ? `SOLO BATTLE / ${difficulty.toUpperCase()}` : `PRIVATE BATTLE / ${room?.code}`}</span><h1>The Runic Grounds</h1></div><div className="round-pill"><span>TURN</span><strong>{String(view.round).padStart(2, '0')}</strong></div></div>
    {mode === 'room' && (!connected || room?.status === 'DISCONNECTED') && <div className="connection-banner" role="status">{!connected ? 'Connection lost. Reconnecting…' : `Rival disconnected. Waiting ${Math.max(0, Math.ceil(((room?.reconnectDeadline ?? now) - now) / 1000))}s…`}</div>}
    {view.round >= 21 && !finished && <div className="sudden-death"><Flame size={16} /> Sudden death · Both cores take 2 damage each combat</div>}
    <div className="arena"><div className="arena-top"><Core view={view} player={enemy} enemy /><div className="enemy-hand" aria-label={`Opponent has ${view.players[enemy].handSize} cards`}><div className="card-backs">{Array.from({ length: view.players[enemy].handSize }, (_, i) => <span key={i}>ᛟ</span>)}</div><small>{view.players[enemy].handSize} CARDS · {view.players[enemy].deckSize} IN DECK</small></div><div className="enemy-mana"><Zap size={16} /><strong>{view.players[enemy].mana}</strong><span>/ {view.players[enemy].maxMana}</span></div></div>
    <div className="lanes">{LANES.map(lane => <div key={lane} className="lane"><span className="lane-label">LANE {['I', 'II', 'III'][lane]}</span><UnitSlot unit={view.players[enemy].lanes[lane]} lane={lane} enemy targetable={isTarget(view.players[enemy].lanes[lane], lane, true)} onClick={() => target(view.players[enemy].lanes[lane], lane, true)} round={view.round} /><div className="lane-divider"><span>✦</span></div><UnitSlot unit={view.players[you].lanes[lane]} lane={lane} enemy={false} targetable={isTarget(view.players[you].lanes[lane], lane, false)} onClick={() => target(view.players[you].lanes[lane], lane, false)} round={view.round} /></div>)}</div>
    <div className="arena-bottom"><Core view={view} player={you} enemy={false} /><div className={`phase-label ${ready ? 'your-turn' : ''}`}><span className="live-dot" />{finished ? 'BATTLE COMPLETE' : ready ? 'YOUR TURN' : 'RIVAL’S TURN'}<small>{finished ? 'The runes have spoken.' : ready ? (view.round === 1 ? 'Turn 1 · Units cannot attack' : 'Your turn · Units attack on turn end') : 'Rival is taking their turn…'}</small></div><div className="mana-display"><div><Zap size={16} /><strong>{view.players[you].mana}</strong><span>/ {view.players[you].maxMana} MANA</span></div><div className="mana-dots">{Array.from({ length: view.players[you].maxMana }, (_, i) => <i key={i} className={i < view.players[you].mana ? 'filled' : ''} />)}</div></div></div>
    <AnimatePresence>{spell && <motion.div key={`spell-${batch}`} className="spell-flash" initial={{ opacity: 0, scale: 0.7 }} animate={{ opacity: [0, 1, 0], scale: [0.7, 1, 1.2] }} transition={{ duration: 1.2 }}><img src={art(CARDS[spell.cardId!].art)} alt="" />{CARDS[spell.cardId!].name}</motion.div>}</AnimatePresence></div>
    <div className="hand-heading"><span className="eyebrow">YOUR HAND <span className="count-badge">{hand.length}/7</span></span><span>{selectedCard ? selectedCard.cardId === 'lightning' ? 'Ready to strike every enemy unit.' : 'Choose a highlighted target.' : 'Select a card to make your move.'}</span></div>
    <div className="hand"><AnimatePresence>{hand.map(card => <Card key={card.id} card={card} selected={card.id === selectedCard?.id} disabled={!ready || !actions.some(a => 'cardInstanceId' in a && a.cardInstanceId === card.id)} onClick={() => selectCard(card)} />)}</AnimatePresence>{hand.length === 0 && <div className="empty-hand">Your hand is empty. Make your board count.</div>}</div>
    {selectedCard?.cardId === 'lightning' && ready && <button className="primary cast-button" onClick={() => { act({ type: 'CAST_SPELL', cardInstanceId: selectedCard.id }); setSelected(null); }}><Zap size={16} /> Cast Lightning · 4 mana</button>}
    </section><aside className="battle-sidebar"><div className="sidebar-intro"><Rune small /><span>THE ART OF<br /><strong>CHOOSING WELL</strong></span></div><section className="turn-panel"><span className="eyebrow">{finished ? 'MATCH FINISHED' : ready ? 'THE NEXT MOVE IS YOURS' : 'WATCH THE BATTLEFIELD'}</span><h2>{finished ? 'Well fought.' : ready ? 'Make it count.' : 'A rival is thinking…'}</h2><p>{finished ? 'Every battle teaches a new lesson.' : ready ? (view.round === 1 ? 'Play units or spells, then end your turn. Note: on Turn 1 units cannot attack.' : 'Play your cards, then end your turn. Your ready units will attack immediately!') : 'Plan your next move while your opponent takes their turn.'}</p><button className="primary end-phase" disabled={!ready} onClick={() => { setSelected(null); act({ type: 'END_PHASE' }); }}>End turn <ArrowRight size={17} /></button></section><section className="deck-info"><Layers3 size={23} /><div><strong>The First Order</strong><span>{view.players[you].deckSize} in deck · {view.players[you].discardSize} discarded</span></div></section><section className="combat-log"><div><span className="eyebrow">BATTLE CHRONICLE</span><span className="live-dot" /></div><div className="log-entries" role="log" aria-label="Combat log">{log.length === 0 ? <p className="log-empty">The battlefield is quiet.<br />Your story starts here.</p> : log.map(entry => ({ ...entry, text: eventText(entry.event, you) })).filter(e => e.text).slice(-14).reverse().map(entry => <p key={entry.id} className={entry.event.type === 'COMBAT_STARTED' || entry.event.type === 'ROUND_STARTED' ? 'log-round' : ''}><span>·</span>{entry.text}</p>)}</div></section><button className="text-button concede" onClick={() => finished ? void leave() : setConfirm(true)}><ArrowLeft size={14} />{finished ? 'Return home' : 'Concede match'}</button></aside>
    {finished && <div className="modal-backdrop"><motion.section className="modal result-modal" role="dialog" aria-modal="true" aria-labelledby="result-title" initial={{ opacity: 0, y: 30 }} animate={{ opacity: 1, y: 0 }}><Crown size={38} /><span className="eyebrow">{view.winner === 'DRAW' ? 'DRAW' : view.winner === you ? 'VICTORY' : 'DEFEAT'} · TURN {view.round}</span><h2 id="result-title">{result}</h2><p>{room?.reason || 'The battle ends. A new strategy begins.'}</p>{mode === 'bot' && <button className="primary" onClick={() => { setSelected(null); startBot(difficulty); }}>Play again <ArrowRight size={16} /></button>}<button className="secondary" onClick={() => void leave()}>Return home</button></motion.section></div>}
    {confirm && <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="concede-title"><h2 id="concede-title">Concede this battle?</h2><p>Your opponent will win this match.</p><button className="primary" onClick={() => { concede(); setConfirm(false); }}>Concede match</button><button className="secondary" onClick={() => setConfirm(false)}>Keep playing</button></section></div>}
  </main>;
}
function Collection({ close }: { close: () => void }) {
  return <div className="modal-backdrop" onClick={close}><section className="modal collection" role="dialog" aria-modal="true" aria-labelledby="collection-title" onClick={e => e.stopPropagation()}><button className="icon-button modal-close" onClick={close} aria-label="Close collection"><X /></button><span className="eyebrow">THE FIRST ORDER / STARTER DECK</span><h2 id="collection-title">Thirty cards. Your strategy.</h2><p>Both players use this deck: 15 units and 15 spells.</p><div className="collection-grid">{Object.values(CARDS).map(c => <div key={c.id}><Card compact card={{ id: c.id, cardId: c.id }} /><span className="quantity">×{DECK.filter(id => id === c.id).length} IN DECK</span></div>)}</div></section></div>;
}
export function App() {
  const { mode, view, sound, toggleSound, error, clearError, connected } = useGame(); const [overlay, setOverlay] = useState<'rules' | 'cards' | null>(null);
  useEffect(() => { restoreRoom(); }, []);
  useEffect(() => { if (!error) return; const timer = setTimeout(clearError, 7000); return () => clearTimeout(timer); }, [error, clearError]);
  useEffect(() => { const listener = (e: KeyboardEvent) => { if (e.key === 'Escape') setOverlay(null); }; window.addEventListener('keydown', listener); return () => window.removeEventListener('keydown', listener); }, []);
  return <><header className="site-header"><div className="brand"><Rune small /><div>CORE BATTLE<span>RUNE OF ODIN</span></div></div><nav aria-label="Main navigation"><button className={mode === 'menu' ? 'nav-active' : ''} onClick={() => setOverlay(null)}>{mode === 'menu' ? 'Play' : 'Battlefield'}</button><button onClick={() => setOverlay('cards')}><Layers3 size={14} /> Cards</button><button onClick={() => setOverlay('rules')}><BookOpen size={14} /> How to play</button></nav><div className="header-right"><span className="connection-label"><span className="live-dot" />{mode === 'room' ? connected ? 'CONNECTED' : 'CONNECTING' : 'READY TO PLAY'}</span><button className="icon-button" onClick={toggleSound} aria-label={sound ? 'Mute sound' : 'Enable sound'}>{sound ? <Volume2 size={18} /> : <VolumeX size={18} />}</button></div></header>{mode === 'menu' ? <Menu /> : view ? <Battle /> : <WaitingRoom />}<AnimatePresence>{error && <motion.div className="error-toast" role="alert" initial={{ opacity: 0, y: -10 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }}><span>{error}</span><button onClick={clearError} aria-label="Dismiss error"><X size={16} /></button></motion.div>}</AnimatePresence>{overlay === 'rules' && <Rules close={() => setOverlay(null)} />}{overlay === 'cards' && <Collection close={() => setOverlay(null)} />}</>;
}
